/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticuloSlugRouteImport } from './routes/articulo.$slug'
import { Route as SeccionSlugRouteImport } from './routes/seccion.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticuloSlugRoute = ArticuloSlugRouteImport.update({
  id: '/articulo/$slug',
  path: '/articulo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SeccionSlugRoute = SeccionSlugRouteImport.update({
  id: '/seccion/$slug',
  path: '/seccion/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articulo/$slug': typeof ArticuloSlugRoute
  '/seccion/$slug': typeof SeccionSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articulo/$slug': typeof ArticuloSlugRoute
  '/seccion/$slug': typeof SeccionSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articulo/$slug': typeof ArticuloSlugRoute
  '/seccion/$slug': typeof SeccionSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/articulo/$slug' | '/seccion/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/articulo/$slug' | '/seccion/$slug'
  id: '__root__' | '/' | '/articulo/$slug' | '/seccion/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticuloSlugRoute: typeof ArticuloSlugRoute
  SeccionSlugRoute: typeof SeccionSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articulo/$slug': {
      id: '/articulo/$slug'
      path: '/articulo/$slug'
      fullPath: '/articulo/$slug'
      preLoaderRoute: typeof ArticuloSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seccion/$slug': {
      id: '/seccion/$slug'
      path: '/seccion/$slug'
      fullPath: '/seccion/$slug'
      preLoaderRoute: typeof SeccionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticuloSlugRoute: ArticuloSlugRoute,
  SeccionSlugRoute: SeccionSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
